### ISSUE TITLE
JDK Versions

### ISSUE THREAD

**Issue by ofluffydev** [FIRST-Tech-Challenge/FtcRobotController#1275]
Oracle released JDK 8 in 2014. It is still supported as an LTS release, but that does not mean it should be used.

Many crucial features and even performance changes on the JVM level have been added since then, while Java 17 is acceptable, we all would appreciate the JDK versions used throughout the FtcRobotController to JDK 21. I can't even use [records](https://www.baeldung.com/java-record-keyword) with Java 8.

Manually changing versions to 21 causes a lot of issues, with many of the classes imported breaking.

**Comment by cmacfarl** [comment]
The internal Java compiler used for OnBotJava is 1.8.   At the present time it is not possible to upgrade because of fundamental JDK implementation changes in 17+ that contain API calls that are not supported by the Google desugaring libraries.  

FIRST has decided that maintaining source compatibility between OnBotJava and Android Studio developed software is desirable and hence will not be changing this at this point. 

There are internal discussions about upgrading OnBotJava but there is no targeted release.
