### ISSUE TITLE
why isn't there an option to use nacon ps4 gamepad?

### ISSUE THREAD

**Issue by legendsobosob** [FIRST-Tech-Challenge/FtcRobotController#1378]

**Comment by Windwoes** [comment]
If the gamepad is PS4-compatible, there is a good chance it will work with the Driver Station software.

Adding explicit support for all available variants of gamepads is (1) not feasible because clone gamepads come and go as the wind blows (2) not particularly useful since only a select list of gamepads are allowed for competition.
