### ISSUE TITLE
Custom Tflite Model Usage #11

### ISSUE THREAD

**Issue by baqwas** [FIRST-Tech-Challenge/FtcRobotController#393]
Ref: POWERPLAY

Zero issue with ConceptTensorFlowObjectDetection.

Yet trying to use the Custom TFOD OpMode with no modifications except for the due changes in _TFOD_MODEL_FILE_ and _TFOD_MODEL_LABELS_:
- ssd_mobilenet_v2_320x320_coco17_tpu_8
- ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu_8
- ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu_8
with ssd_mobilenet_v2_label_map.txt

and:
- detect.tflite
with labelmap.txt

The first set has zero object detection/classifications with common images from public domain that "could be interpreted" as one of the labels. The second set will very, very occasionally respond with the label **sheep** for every object it classifies! (Yes, I understand that the white space on the signal sleeve gets in way!) but its reproducibility is also low. (The basic end-user dilemma - _Hello, I've a problem. Sorry, I can't reproduce it_).

I don't have an exhaustive list of parameters to tweak for the FTC TFOD OpModes. Just winging it presently with changes to _magnification_ and _ambient lighting_. Have run the gauntlet of OpModes for webcam controls but see nothing other than AWB and Gain to tweak from a webcam perspective. Perhaps there are some other parameters that I am ignorant about. I've seen a few in the corresponding Javadoc but would love to get an expert to chime in, please.

Is there a set of images that an end-user can use for a sanity test to confirm any one of the above models? Just need a _few_ to help the team members sustain their interest in ML for FTC work. They are presently not believing that there is light at the end of this tunnel. Thanks.

Kind regards.

**Comment by texasdiaz** [comment]
I'm not sure exactly how your code is constructed, but let me offer my initial errors when I implemented a solution using the models:

(1) You actually have to include every single label, in the order that they're specified within the label map, in your list of labels. The list of labels IS NOT to tell TensorFlow what to look for (as even I understood it to be initially) - TensorFlow doesn't actually understand the labels and doesn't even read the labels. TensorFlow returns an index into the list of labels you provided; it expects the list of labels to be exactly the list it was trained with, in the exact order it trained them in. Hence it will internally return "1" or "23" or "47", and not a label (no, we don't return that value for you to see either). The TensorFlow APIs then use your list of labels to index what TensorFlow told it, and returns the label it found there. If a label has "????", that's a valid label and also must be included in the label map (the label is a "dummy label" that's used for background image data, but whatever). So I know it's a pain to introduce 84 or more labels when you're only expecting to recognize 2-3 objects, but that's the price of doing business.

(2) Do you realize that you can see what TensorFlow sees? Sorta. We allow you to view an image preview on the Driver Station, but only when using a Vuforia or TensorFlow enabled program, and only in Init mode (once you click "Run" the option goes away). Just Init your opmode, and then press the three dots menu. You will find a new "Camera Stream" option that allows you to see the camera view with the detections on top (used for aiming your robot's camera). You have to tap the screen to update the image - this is done so that camera streaming on a hundred or more phones doesn't clog the available bandwidth at big tournaments.

(3) The [COCO dataset](https://cocodataset.org/#explore) is the standard dataset to train the Model Zoo models. You can see all of the images used to train the model, grouped by classification.

Hope this helps.
