### ISSUE TITLE
Tensorflow lite

### ISSUE THREAD

**Issue by flemmii** [FIRST-Tech-Challenge/FtcRobotController#688]
Hi,
I use tensorflow lite for my camera detction but after the 8.2.0 update it doesn't work anymore because there is a native library missing which has the function nativeDoNothing for example. It looks like the ftc sdk refuses to add these libraries is there a way I can add them anyway to my build process?
Regards
flemmi

**Comment by texasdiaz** [comment]
In 8.2.0 and subsequently in 9.0 we updated the TensorFlow dependencies in order to support newer models. When you say you "use TensorFlow Lite for camera detection" are you using the FTC SDK functions, or are you using additional libraries? When you create your models, are you using the FTC Machine Learning Toolchain or are you creating them using an external tool?

**Comment by flemmii** [comment]
I am using google teachable machine and https://github.com/OutoftheBoxFTC/EasyTensorflowAPI to use it.

**Comment by texasdiaz** [comment]
I'm sorry, we do not provide support for those platforms or tools. You need to file an issue with the EasyTensorflowAPI project, we cannot help you with that.
