### ISSUE TITLE
Connectivity error whenever i run code related to huskylens

### ISSUE THREAD

**Issue by msover** [FIRST-Tech-Challenge/FtcRobotController#747]
I was playing around with the huskylens sensor sample class and whenever i ran it i got "Error communicating with I2C device(s) 'huskylens'. Check your wiring and configuration" on the driver station app. I tried using the same I2C port and cable for a distance sensor and it worked perfectly.
Any ideas ?

**Comment by texasdiaz** [comment]
The pin configuration on the HuskyLens and on the Control Hub are not compatible. There are 4 wires on the I2C cable:

- Power
- Ground
- Data
- Clock

The HuskyLens has the Power/Ground pins backwards and the Data/Clock pins backwards (that's all 4 pins not in the same place). Hence, the standard cable for a REV sensor cable WILL NOT work perfectly even though the connectors are the same.

I took the standard cable that ships with the HuskyLens and a standard REV cable and connected them together with One-to-One Lever connectors so that the pins are correct. This is a good example demonstrating the difference, though if you're handy with small tools you can pop out and reconnect the pins on the connectors to achieve the same goal. Here's what it looks like:

![image](https://github.com/FIRST-Tech-Challenge/FtcRobotController/assets/5846611/3aa2c481-58c5-4c2a-ad39-282e9e56ef35)

You can see that the wire colors on both connectors are almost the same (instead of a white wire it's a green one on the HuskyLens connector) but they're in the wrong order on the HuskyLens.

**Comment by baqwas** [comment]
@texasdiaz, I wish I had known about lever wire connectors. Would've saved me some soldering (which is often _dry_ in my case). Thanks for highlighting the proper solution.

Regards.

**Comment by baqwas** [comment]
@msover,

There is a comment in the example OpMode for HuskyLens that you are presumably already aware of:

> However, sometimes it's unclear why a device reports as
>          * failing on initialization. 
> 

I too get this message but only once at the first INIT. Thereafter it seems to go away. (The HuskyLens is connected to an Expansion Hub whose firmware is not current for CENTERSTAGE).

I am still working my way through the example OpMode but I wanted to give you heads-up on my experience that the documentation comment is significant. (Also, I'm not using the Lever connector; I soldered the wire and one can never tell with Al conductors how good the soldering can be).

Regards.

**Comment by texasdiaz** [comment]
I too frequently get a fail on first initialization after boot, but it rarely affects device performance - I don't get any errors afterwards, and the device seems to function properly. Others on the team who have tested the HuskyLens have not reported this issue. I'm not exactly sure why the failure occurs, but if you can find a procedure to faithfully reproduce this error we can look into it more. I've tried and it seems too random for me, maybe I just haven't nailed the sequence or timing.

**Comment by baqwas** [comment]
Hello @texasdiaz,

Personally, I am not concerned about this _initial_ message once I got the wires correctly reversed. Since it does not recur (team programmer confirmed but unfortunately same robot same HuskyLens with a few extra telemetry statements) with repetitive use of the OpMode in the same session, it is not an issue for our team. Thanks.

Regards.
